<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * @package Stencil
 * @subpackage Theme
 */

// Make sure WordPress is loaded.
if ( ! function_exists( 'add_filter' ) ) {
	header( 'Status: 403 Forbidden' );
	header( 'HTTP/1.1 403 Forbidden', true, 403 );
	exit();
}

if ( ! function_exists( 'get_stencil' ) ) {
	$theme_name = wp_get_theme()->get( 'Name' );

	header( $_SERVER['SERVER_PROTOCOL'] . ' 500 Internal Server Error', true, 500 );
	trigger_error( sprintf( 'The active theme (%s) requires the "Stencil" plugin to be activated.', $theme_name ), E_USER_ERROR );

} else {

	get_stencil()->run();

}

die();
